name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

   - name: Build the hello-world Docker image
     run: |
        docker build . --tag ghcr.io/minhle1507/my-service01/hello-world:latest
        docker run ghcr.io/my-service01/hello-world:latest
        docker push ghcr.io/my-service01/hello-world:latest
